spring.application.name=server

# Port Number
server.port=9000

# Database
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=1234
